### PR TITLE
Add COVID-19 cancellation reason and cancellation reason description

### PR DESCRIPTION
**Pull request by mphalliday**

### CODE REVIEW

**Comment by jfriedlaender** [comment]
What is this for?

**Comment by JohnColvin** [comment]
we send code and description on other endpoints that have things like this. but this is part of a future plan to deprecate codes and do with description only here. which would allow accounts to customize cancellation reasons

long discussion here https://redguava.slack.com/archives/CV46DS0PM/p1584475764128300

**Comment by hagen** [comment]
@mphalliday good to go out?

**Comment by mphalliday** [comment]
Yup! 👍

**Pull request merged**
